name = "blog-likes"
account_id = "a11009e7a2f9325714628596d6441fad"
compatibility_date = "2025-04-01"
main = "src/index.js"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "blog-likes"
database_id = "9e466e9c-86f1-46d8-860b-b92783556eaa"

[observability.logs]
enabled = true


